---
- hosts: all
  vars:
    certbot_admin_email: "{{ lookup('env', 'GHOST_ALERT_EMAIL') }}"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - hackandslash.blog
    nginx_upstreams:
      - name: ghost
        strategy: "ip_hash" # "least_conn", etc.
        servers:
          - "localhost:2368"
    nginx_vhosts:
      - listen: "80"
        server_name: "hackandslash.blog"
        return: "301 https://hackandslash.blog$request_uri"
        filename: "hackandslash.blog.80.conf"
      - listen: "443 ssl http2"
        server_name: "hackandslash.blog"
        filename: "hackandslash.blog.443.conf"
        extra_parameters: |
          location / {
            proxy_buffering    off;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Scheme $scheme;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $http_host;
            proxy_set_header   X-Forwarded-Proto https;
            proxy_pass         http://ghost;
          }

          ssl_certificate     /etc/letsencrypt/live/hackandslash.blog/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/hackandslash.blog/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  roles:
    - role: geerlingguy.certbot
    - role: geerlingguy.docker
    - role: geerlingguy.nginx
    - role: ghost
